### ISSUE TITLE
name shows up as nothing if no display name is set (in the welcome back text)

### ISSUE THREAD

**Issue by sdpj** [carrevue/OpenSB#240] opened 2024-08-08 23:54 UTC
i feel like it cant be that hard to just make it use the username if theres no display name

![YQOXTzc](https://github.com/user-attachments/assets/b55870e4-23fb-42d1-b2db-1a313cb89fb4)

**Comment by PF94** [comment] 2024-08-08 23:55
because in theory, your display name should be kit.

![image](https://github.com/user-attachments/assets/7a7fc5af-f08e-4e16-8e6a-47616743f81b)

for example: my display name and username are both chaziz

**Comment by PF94** [comment] 2024-08-08 23:55
also this is a duplicate of #234

**Closed as completed by PF94** 2024-08-08 23:55 UTC
Labels: duplicate
